<a href="https://colab.research.google.com/github/rakj01/PythonLibraries/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np

In [4]:
#normal addition
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
z = []
for i, j in zip(x, y):
  z.append(i + j)
print(z)

[6, 8, 10, 12]


In [5]:
z1 = np.add(x, y)
print(z1)

[ 6  8 10 12]


In [7]:
def myadd(x, y):
  return x + y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [8]:
print(type(np.add))

<class 'numpy.ufunc'>


In [9]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [10]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [11]:
arr1 = np.array([10, 11, 12])
arr2 = np.array([13, 14, 15])
newarr = np.add(arr1, arr2)
print(newarr)

[23 25 27]


In [12]:
newarr1 = np.subtract(arr1, arr2)
print(newarr1)

[-3 -3 -3]


In [13]:
newarr2 = np.multiply(arr1, arr2)
print(newarr2)

[130 154 180]


In [14]:
newarr3 = np.divide(arr1, arr2)
print(newarr3)

[0.76923077 0.78571429 0.8       ]


In [15]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([3, 5, 10, 8, 2])
newarr4 = np.power(arr1, arr2)
print(newarr4)

[           1000         3200000 590490000000000   6553600000000
            2500]


In [16]:
newarr5 = np.mod(arr1, arr2)
print(newarr5)

[1 0 0 0 0]


In [17]:
newarr6 = np.remainder(arr1, arr2)
print(newarr6)

[1 0 0 0 0]


In [18]:
newarr7 = np.divmod(arr1, arr2)
print(newarr7)

(array([ 3,  4,  3,  5, 25]), array([1, 0, 0, 0, 0]))


In [20]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr8 = np.absolute(arr)
print(newarr8)

[1 2 1 2 3 4]


In [22]:
#return the float number closest to zero
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [23]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [24]:
arr = np.around(3.1666, 2)
print(arr)

3.17


In [25]:
#rounds off decimal to nearest lower integer.
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [26]:
#rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


- NumPy provides functions to perform log at the base 2, e and 10.


In [27]:
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [28]:
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [29]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [30]:
from math import log
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

1.7005483074552052


In [31]:
#summestions
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [32]:
#summestion over axis
newarr1 = np.sum([arr1, arr2], axis=1)
print(newarr1)

[6 6]


In [33]:
#cummulative sum
newarr2 = np.cumsum(arr1)
print(newarr2)

[1 3 6]


In [37]:
arr1 = np.array([1, 2, 3, 4])
newarr = np.prod(arr1)
print(newarr)

24


In [38]:
arr2 = np.array([5, 6, 7, 8])
newarr1 = np.prod([arr1, arr2])
print(newarr1)


40320


In [39]:
newarr2 = np.prod([arr1, arr2], axis=1)
print(newarr2)

[  24 1680]


In [40]:
newarr3 = np.cumprod(arr1)
print(newarr3)

[ 1  2  6 24]


In [41]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [42]:
newarr1 = np.diff(arr, n=2)
print(newarr1)

[  5 -30]


The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [43]:
print(np.lcm(4, 6))

12


In [46]:
arr = np.arange(1, 11)
x = np.lcm.reduce(arr)
print(x)

2520


The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers

In [47]:
print(np.gcd(6, 9))

3


In [48]:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


Trigonometric Functions
- take values in radians

In [49]:
x = np.sin(np.pi/2)
print(x)

1.0


In [50]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


- radians values are pi/180 * degree_values.

In [51]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [52]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [53]:
print(np.arcsin(1.0))

1.5707963267948966


In [54]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


- NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [55]:
print(np.hypot(3, 4))

5.0


In [57]:
print(np.sinh(np.pi/2))

2.3012989023072947


In [58]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)


[2.50917848 1.60028686 1.32460909 1.20397209]


In [59]:
arr = np.array([0.1, 0.2, 0.5])
x = np.arcsinh(arr)
print(x)

[0.09983408 0.19869011 0.48121183]


A set in mathematics is a collection of unique elements.

In [60]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [61]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


In [62]:
newarr1 = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr1)

[3 4]


To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [63]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [65]:
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]
